exports.HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500
};

exports.EVENT_STATUS = {
  UPCOMING: 'upcoming',
  COMPLETED: 'completed'
};

exports.JWT_EXPIRES_IN = '7d';
exports.BCRYPT_SALT_ROUNDS = 12;
exports.NOTIFICATION_TIMING = 30;
